name: commits_history
description: In this application you can see the commits you have made in a GitHub repository.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core

  # Critical
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_platform_widgets: ^5.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  go_router: ^13.2.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1

  # Can be replaced
  auto_size_text: ^3.0.0 # Check if this is necessary for this project
  flutter_dotenv: ^5.1.0

  # Google Icons
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
